const fs=require('fs')
const man=JSON.parse(fs.readFileSync('scripts/flags/cf/manifest.json','utf8'))
const map={}
for(const [name,p] of Object.entries(man)){ map[name.replace(/ /g,'_')]=p }
const keys=Object.keys(map).sort()
const lines=keys.map(k=>`  ${JSON.stringify(k)}: ${JSON.stringify(map[k])},`)
fs.writeFileSync('src/data/hostedFlags.ts',
`// AUTO-GENERATED by scripts/flags/genhosted (reads the self-host manifest).
// Supplements LOCAL_FLAGS: maps a Wikimedia Commons filename (space→underscore)
// to a self-hosted copy under /cf/. Anything absent falls back to the live
// Commons hotlink, so a partial set is always safe. Do not hand-edit.
export const HOSTED_FLAGS: Record<string, string> = {
${lines.join('\n')}
}
`)
console.log('HOSTED_FLAGS entries:',keys.length)
