// Produce src/data/localFlags.ts from on-disk images + repairs.json. Network-free
// and throttle-proof: each flag resolves to the best available source.
//
//   LIVE flag        -> local file if downloaded, else OMITTED (falls back to the
//                       original working Wikimedia hotlink — no regression).
//   REPAIRED dead    -> local fix- file if downloaded, else a Wikimedia hotlink to
//                       the CORRECT replacement file (loads correctly, just not
//                       self-hosted yet). Either way the flag is fixed.
//   UNREPAIRABLE/    -> "" so the UI shows "No flag" and quizzes skip it.
//   vetoed repair
import { readFileSync, writeFileSync, existsSync, mkdirSync, readdirSync, statSync } from "node:fs"
import { assignLiveSlugs, slugify } from "./lib.mjs"

const ROOT = new URL("../../", import.meta.url)
const OUT_DIR = new URL("public/flags/wm/", ROOT)
mkdirSync(OUT_DIR, { recursive: true })
const here = (p) => new URL(p, import.meta.url)
const keyOf = (arg) => arg.replace(/ /g, "_")
const hotlink = (title) =>
  `https://commons.wikimedia.org/wiki/Special:FilePath/${title.replace(/^File:/, "").replace(/ /g, "_")}`

const report = JSON.parse(readFileSync(here("./audit-report.json")))

// Index existing files by slug.
const bySlug = new Map()
for (const f of readdirSync(OUT_DIR)) {
  if (statSync(new URL(f, OUT_DIR)).size > 0) bySlug.set(f.replace(/\.[a-z0-9]+$/i, ""), f)
}

// ── Live flags ──────────────────────────────────────────────────────────────
const { titleToSlug } = assignLiveSlugs(report)
const map = {}
let liveLocal = 0
for (const r of report) {
  if (!r.exists) continue
  const file = bySlug.get(titleToSlug.get(r.title))
  if (file) {
    map[keyOf(r.arg)] = `/flags/wm/${file}`
    liveLocal++
  }
  // else: omit -> fp()/wiki() keeps the original (working) Commons hotlink.
}

// Manually vetoed repairs — the auto-matcher accepted a wrong-entity/type file
// (city→state, city→county, governorate→municipality, or a flag-MAP, or only an
// obsolete historical flag). These are demoted to "no flag".
const REJECT_REPAIRS = new Set([
  "Flag of Oklahoma City.svg",
  "Flag of Jersey City, New Jersey.svg",
  "Flag of Dallas, Texas.svg",
  "Flag of Chon Buri Province.svg",
  "Flag of Basra Governorate.svg",
  "Flag_of_Seattle,_Washington.svg",
  "Flag_of_Nashville,_Tennessee.svg",
  "Flag_of_Louisville,_Kentucky.svg",
  "Flag_of_Fort_Worth,_Texas.svg",
  "Flag_of_Akron,_Ohio.svg",
  "Flag_of_Boise,_Idaho.svg",
  "Flag_of_Lansing,_Michigan.svg",
  "Flag_of_Ann_Arbor,_Michigan.svg",
])

// ── Repairs + unrepairable ──────────────────────────────────────────────────
let repairedLocal = 0
let repairedHotlink = 0
let removed = 0
if (existsSync(here("./repairs.json"))) {
  const data = JSON.parse(readFileSync(here("./repairs.json")))
  const repairs = data.repairs.filter((r) => !REJECT_REPAIRS.has(r.arg))
  const vetoed = data.repairs.filter((r) => REJECT_REPAIRS.has(r.arg))
  for (const r of repairs) {
    const file = bySlug.get(`fix-${slugify(r.finalTitle)}`)
    if (file) {
      map[keyOf(r.arg)] = `/flags/wm/${file}`
      repairedLocal++
    } else {
      map[keyOf(r.arg)] = hotlink(r.finalTitle || r.chosen)
      repairedHotlink++
    }
  }
  for (const u of [...data.unrepairable, ...vetoed]) {
    map[keyOf(u.arg)] = ""
    removed++
  }
}

// ── Emit module ─────────────────────────────────────────────────────────────
const keys = Object.keys(map).sort()
const lines = keys.map((k) => `  ${JSON.stringify(k)}: ${JSON.stringify(map[k])},`)
writeFileSync(
  new URL("src/data/localFlags.ts", ROOT),
  `// AUTO-GENERATED by scripts/flags/generate.mjs — do not edit by hand.
// Maps a Wikimedia Commons filename (as passed to fp()/wiki(), space->underscore)
// to its image source:
//   "/flags/wm/…"  self-hosted local copy
//   "https://…"    a working Wikimedia hotlink to the CORRECT (repaired) file
//                  that hasn't been self-hosted yet
//   ""             dead link with no replacement — treated as "no flag"
// Filenames absent here fall back to the original live Commons hotlink, so a
// partial self-hosted image set is always safe.
export const LOCAL_FLAGS: Record<string, string> = {
${lines.join("\n")}
}
`,
)

console.log(
  `Map entries: ${keys.length} — live-local ${liveLocal}, repaired-local ${repairedLocal}, ` +
    `repaired-hotlink ${repairedHotlink}, removed→"" ${removed}.`,
)
console.log("Wrote src/data/localFlags.ts")

// ── Diagnostics data for the in-app QA list (Settings → Flag Check) ──────────
const clean = (arg) => arg.replace(/\.(svg|png|gif|jpe?g)$/i, "").replace(/_/g, " ")
if (existsSync(here("./repairs.json"))) {
  const d = JSON.parse(readFileSync(here("./repairs.json")))
  const fixed = d.repairs
    .filter((r) => !REJECT_REPAIRS.has(r.arg))
    .map((r) => ({ label: clean(r.arg), url: map[keyOf(r.arg)] }))
    .filter((x) => x.url)
    .sort((a, b) => a.label.localeCompare(b.label))
  // Candidate previews: Commons search hits that *might* be the right flag, for
  // the user to eyeball. Drop photos, maps, seals, logos and other non-flags.
  const JUNK = /\.(jpe?g|tiff?)$|flag.?map|map of|outline|\blabel\b|corner|disputed|simple map|\bseal\b|coat of arms|\blogo\b|\bemblem\b|locator|orthographic|\btemple\b|\bvisit\b|assembly|parliament|construction|\brugby\b|\bpin\b|\bicon\b|background|\bday\b/i
  // Richer cross-wiki candidates (Commons + en.wikipedia, with real URLs) when
  // available; otherwise fall back to the Commons-only string candidates.
  const extra = existsSync(here("./candidates-extra.json"))
    ? JSON.parse(readFileSync(here("./candidates-extra.json")))
    : {}
  const candsFor = (u) =>
    extra[u.arg]?.length
      ? extra[u.arg].slice(0, 5)
      : (u.candidates || [])
          .filter((c) => /flag|bandera|drapeau|bandiera|vlag/i.test(c) && !JUNK.test(c))
          .slice(0, 5)
          .map((c) => ({ file: c, url: hotlink(c) }))
  const missing = [...d.unrepairable, ...d.repairs.filter((r) => REJECT_REPAIRS.has(r.arg))]
    .map((u) => ({ arg: u.arg, label: clean(u.arg), cands: candsFor(u) }))
    .sort((a, b) => a.label.localeCompare(b.label))
  // "New" tab: recently added/recovered flags to verify they load. Covers every
  // recovered repair (lenient + user picks) plus flags added directly in the data.
  const EXTRA_RECENT = [
    { label: "Nevis (St Kitts & Nevis)", key: "Flag_of_Nevis.svg" },
    { label: "Izabal (Guatemala)", key: "Flag_of_Izabal_Department.svg" },
  ]
  const recent = [
    ...d.repairs.filter((r) => r.recovered && !REJECT_REPAIRS.has(r.arg)).map((r) => ({ label: clean(r.arg), url: map[keyOf(r.arg)] })),
    ...EXTRA_RECENT.map((e) => ({ label: e.label, url: map[e.key] || hotlink(e.key) })),
  ].filter((x) => x.url).sort((a, b) => a.label.localeCompare(b.label))

  writeFileSync(
    new URL("src/data/flagDiagnostics.ts", ROOT),
    `// AUTO-GENERATED by scripts/flags/generate.mjs — temporary QA aid.
// FIXED: dead links now repaired (these images should load). MISSING: dead
// links with no confirmed replacement (rendered from their original Wikimedia
// name, so most will be broken — that is the "needs a filename" to-do list).
export interface DiagCand { file: string; url: string }
export interface DiagFlag { label: string; url: string; cands?: DiagCand[] }
export interface MissingFlag { arg: string; label: string; cands: DiagCand[] }
export const FIXED_FLAGS: DiagFlag[] = ${JSON.stringify(fixed, null, 0)}
export const MISSING_FLAGS: MissingFlag[] = ${JSON.stringify(missing, null, 0)}
export const RECENT_FLAGS: DiagFlag[] = ${JSON.stringify(recent, null, 0)}
`,
  )
  console.log(`Wrote src/data/flagDiagnostics.ts (fixed ${fixed.length}, missing ${missing.length})`)
}
